import 'package:flutter/material.dart';

import '../../activities/retailing_screen.dart';

class ConstArray {
  List<String> brand = [
    'Brand 1',
    'Brand 2',
    'Brand 3',
    'Brand 4',
    'Brand 5',
  ];
  List<String> category = [
    'Category 1',
    'Category 2',
    'Category 3',
    'Category 4',
    'Category 5',
  ];

  List<String> brandform = [
    'Brand Form 1',
    'Brand Form 2',
    'Brand Form 3',
    'Brand Form 4',
    'Brand Form 5',
  ];

  List<String> subBrand = [
    'Sub-brand 1',
    'Sub-brand 2',
    'Sub-brand 3',
    'Sub-brand 4',
    'Sub-brand 5',
  ];

  List<SalesData> data = [
    SalesData(0, 15),
    SalesData(1, 17),
    SalesData(2, 16),
    SalesData(3, 18),
    SalesData(4, 19),
    SalesData(5, 23),
  ];

  List<SalesData> data1 = [
    SalesData(0, 12),
    SalesData(1, 19),
    SalesData(2, 16),
    SalesData(3, 25),
    SalesData(4, 19),
    SalesData(5, 2),
  ];

  List<String> allIndia = [
    'All India',
  ];
  List<String> division = [
    'North-East 1',
    'South-West',
  ];

  List<String> cluster = [
    'Cluster 1',
    'Cluster 2',
    'Cluster 3',
    'Cluster 4',
    'Cluster 5',
  ];

  List<String> site = [
    'Site 1',
    'Site 2',
    'Site 3',
    'Site 4',
    'Site 5',
  ];

  List<String> branch = [
    'Branch 1',
    'Branch 2',
    'Branch 3',
    'Branch 4',
    'Branch 5',
  ];

  List<String> month = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
  ];

  List<String> monthFull = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ];

  List<String> categoryFilter = [
    "Select..",
    "Unknown",
    "FEM CARE",
    "PERSONAL CARE (OS)",
    "APPLIANCES",
    "Batteries",
    "HEALTH CARE",
    "GROOMING",
    "Personal Care (GIL)",
    "ORAL CARE",
    "AIRCARE",
    "Unknown ER",
    "FABRIC CARE",
    "SKIN CARE",
    "HAIR CARE",
    "Baby Care",
    "FABRIC & HOME CARE"
  ];

  List<String> brandFilter = [
    "Select..",
    "Pantene",
    "Unknown",
    "Liners",
    "365 DE",
    "Gillette Series",
    "Gillette Sport",
    "Gillette Presto Intl",
    "Dummy Brand",
    "Fusion PC",
    "HERBAL ESSENCES",
    "BabyRub",
    "Guard",
    "Inhaler",
    "Gillette Vector Plus",
    "Gillette Mach3",
    "ORAL B",
    "Tide",
    "7 O Clock PII",
    "Fusion",
    "Blue II",
    "Blue 3",
    "Duracell",
    "Action 500",
    "Braun",
    "H&S",
    "Winner",
    "Gillette Sensor Excel",
    "Wilkinson Sword",
    "7 O Clock",
    "Whisper",
    "Ariel",
    "AmbiPur",
    "Pampers Liberty",
    "King C Gillette",
    "Gillette",
    "Male Body",
    "Gillette Labs",
    "Ariel Liquid",
    "Skinguard",
    "Gillette G II Plus",
    "Pampers",
    "Olay",
    "Gillette Satin Care",
    "Mach-3 Turbo",
    "Pantene Oil Replacement",
    "WS Device",
    "Venus",
    "Pantene Oil",
    "Vaporub",
    "Vector3",
    "Pampers Baby Wipes",
    "Satin Care",
    "VCD",
    "Vaporub Xtra Strong",
    "Wilman",
    "Old Spice",
    "Unknown ER",
    "Vicks",
    "Vicks 3in1"
  ];

  List<String> sbf = [
    "Select..",
    "AmbiPur Car Refills",
    "Ariel Matic Liquid",
    "Excel Razor",
    "Fusion Carts eC",
    "Ariel New Matics",
    "7 Other System Cart",
    "7 Other Disp",
    "OB POC Handle",
    "Natural Aura Cream",
    "Braun IPL",
    "Mach3 H+2 eC",
    "Herbal Conditioner",
    "OB WS Fresh Clean",
    "AmbiPur Air Effects",
    "OB 123 Neem",
    "BabyRub",
    "SkinGuard Cart",
    "AmbiPur Set Refresh",
    "Active Baby",
    "Mosquito Guard Pants",
    "AmbiPur CNE",
    "Ariel Base Bags",
    "Du AA",
    "DCL Facewash",
    "Old Spice After Shave",
    "Du AAA",
    "OB Pro health paste",
    "AP Cream",
    "AmbiPur Vent Clips",
    "Blue II",
    "Ariel PerfectWash",
    "H&S Conditioner Sachets",
    "AP Cleanser",
    "Action 500",
    "Braun Face Trimmer",
    "AmbiPur Aerosols",
    "Excel Cart",
    "Guard Cream",
    "OB Complete Clean",
    "H&S Small Sachet",
    "Guard Gel",
    "DE Super Box",
    "Deodorants",
    "AmbiPur Car Starters",
    "Tide Base Bags",
    "Gillette MM Device",
    "OB 123 Natural 3in1",
    "H&S Conditioner",
    "Mach-3 Start Rzr",
    "KCG",
    "AmbiPur Home Gel",
    "Fusion Gel",
    "AP Eye Gel",
    "Fusion Cart",
    "Gillette Foam",
    "AmbiPur Car Gel",
    "DE Blades 365",
    "7 DE Rzr",
    "Braun Multi Grooming Kit",
    "After Shave Splash",
    "Natural White Cream",
    "Braun Body Groomer",
    "Mach-3 Start Cart",
    "Gillette 5 Sport",
    "Olay Retinol",
    "NW Cream",
    "DE Uti Boxes",
    "OB POC Refill",
    "OB Prepack",
    "GPI",
    "OB Cavity Defense Promo",
    "Mach-3 Cart",
    "Oral Care Spl",
    "Ariel Ultramatic",
    "Braun Male Key Parts",
    "Vector3 Razor",
    "Ariel Sachets",
    "Gillette 4in1 GP Pack",
    "OB Devices",
    "Guard3 Carts",
    "Guard Razor",
    "Gillette GP Pack",
    "Pampers Splashers",
    "OB Fresh Clean",
    "Premium Pants",
    "Gillette Heated Razor",
    "Ariel Base Rs. 10",
    "OB WS Cavity Defense",
    "Blue 3",
    "Ariel Canister",
    "Braun Hair Dryers & Curlers",
    "Oral B Box",
    "Braun Beard Trimmer",
    "Gillette Heated Carts",
    "Natural White Sachets",
    "OB Prohealth New",
    "M3T Carts eC",
    "Guard Cart",
    "H&S 2-in-1 Bottle",
    "Turbo Mach-3 Cart",
    "Tide Naturals",
    "Pantene Conditioner Bottles",
    "OB Sensitive",
    "Natural White Cleanser",
    "Pampers Liberty",
    "Ariel PODS",
    "G Series Foam & Gel",
    "Ariel Front O Mat",
    "Mach3 Carts eC",
    "OB Fresh Clean Chrcl",
    "Olay Mens Skin Multi Solutions",
    "Fusion Gift Pack",
    "Braun Shavers",
    "Olay Masks",
    "Ariel Bucket",
    "OB H32 Paste",
    "OB WS Complete Clean",
    "OB Cavity Defense",
    "Power Oral Care",
    "Pantene Conditioner Sachets",
    "Vector Rzr",
    "Guard Header",
    "Tide Plus",
    "OB Shiny Clove",
    "Old Spice Deodorants",
    "Pantene Bottles",
    "OB Shiny Clean",
    "Braun Epilator",
    "Gillette Shave Brush",
    "Inhaler",
    "Old Spice Shaving Cream",
    "VCREM",
    "OB 3in1 Herbs",
    "H&S Supreme Conditioner Bottles",
    "Male Body Cart",
    "Whisper Thick",
    "OB PH Dentist",
    "Guard3 Rzr",
    "PureZZZS",
    "Pampers Pants-LCPs (1s-2s-4s)",
    "OB Kids Low",
    "Mach-3 Rzr",
    "Gillette Shaving Crm",
    "G Other System Cart",
    "Guard Foam",
    "Olay Collagen",
    "Pampers Pants-Mid Packs",
    "Tide Sachets",
    "Total Effects Cream",
    "OB Prohealth",
    "Proglide Carts eC",
    "OB WS CD Bac Fight",
    "Olay AHA",
    "Tide Ultra Machine",
    "Herbal Bundle Pack",
    "H&S Sachets",
    "Fusion Raz",
    "OB Cav DefBlack",
    "Zzzquil",
    "SS Blades",
    "H&S Conditioner Bottle",
    "Herbal Shampoo",
    "Oral-B Manual",
    "OB Sensitive Promo",
    "Pampers Pants-Big Packs",
    "Olay Super Serums",
    "ProGlide Flexbal Rzr",
    "H&S Supreme Bottles",
    "Tide Liquid",
    "Vicks",
    "RG Cream",
    "Splty & Torch",
    "H&S Bottles",
    "Moisturizing Cream",
    "OB 3in1 Natural Card",
    "Pampers Pants",
    "Venus Snap",
    "ProGlide Cart",
    "Other System Rzr",
    "OB 3in1 GP card",
    "Tide Bar",
    "OB Cav Def Charcoal",
    "S Other Disp",
    "Pampers Wipes",
    "Old Spice RTM",
    "Olay Eyes",
    "OB 123 Clove",
    "Gill Super Saver Pack",
    "W Other Disp",
    "SkinGuard Raz",
    "Vector3 Cart",
    "Old Spice Shave Foam",
    "Tide FreshClean",
    "Olay Whips",
    "Olay Minis",
    "VCD",
    "OB 4in1 Natural Card",
    "OB CD Bac Fight",
    "WR Cream",
    "OB EF gel paste",
    "OB Kids Top",
    "OB WS FreshCln Neem",
    "Whisper Ultra Soft",
    "Pampers Imax",
    "Tide PODS",
    "Pampers Preemies",
    "Male Body Rzr",
    "SC Series Foam & Gel",
    "TE FW Cream",
    "Moisturizing Lotion",
    "OB Kids",
    "Winner DE Blades",
    "Pantene OR",
    "OB Classic Super Clean",
    "Pantene Oil",
    "Tide Bucket",
    "Olay Luminous",
    "OB ProhealthN6+1Free",
    "Vaporub",
    "W Other System Cart",
    "Pantene Sachets",
    "Whisper Choice Ultra",
    "VVP",
    "Venus Disposable",
    "Vaporub Xtra Strong",
    "Whisper Liners",
    "Unknown",
    "Pantene 2in1 Bottles",
    "Venus Cart",
    "OB 3in1 Combo Pk",
    "WS Sticker",
    "Venus Razor",
    "SP Blades",
    "Old Spice After Shave Atomizer",
    "Presto3",
    "Wilkson DE Blades",
    "Vicks Multi Pain",
    "OB Shiny Clean Promo",
    "Whisper Choice",
    "Total Effects Cleanser",
    "Vector Cart",
    "Whisper Ultra",
    "OB Shiny Tulsi",
    "Unknown ER",
    "OB WS Shiny Clean",
    "Vicks 3in1",
    "Tube Shave Gel",
    "Turbo Mach-3 Rzr"
  ];

  List<String> sbfg = [
    "Select.."
    "Saurav Grp 02",
    "Saurav Grp 04",
    "Unknown"
  ];

  List<dynamic> siteNewList= [
    "Bhutan",
    "Unknown",
    "Pune",
    "Cochin",
    "Bengal",
    "West UP",
    "Nepal",
    "Raipur",
    "NEC",
    "Hyderabad",
    "Bangalore",
    "Nagpur",
    "Jharkhand",
    "Chennai",
    "Odisha",
    "East UP",
    "TEST DEHRADUN",
    "Marathwada",
    "Bihar",
    "Madurai",
    "Surat",
    "Andaman",
    "Ahmedabad",
    "Kashmir",
    "Coimbatore",
    "Lucknow",
    "Kanpur",
    "Indore",
    "Rajasthan",
    "Sri Lanka",
    "Bhopal",
    "Goa",
    "Jammu",
    "Delhi",
    "Punjab",
    "Haryana",
    "Vijayawada",
    "Mumbai",
    "Uttarakhand",
    "Tirupati"
  ];

  List<dynamic> clusterNewList = [
    "NULL",
    "Nepal",
    "HR",
    "MH.GJ.GA.NAG",
    "TN",
    "NE",
    "RJ.MP.CG",
    "KL",
    "PUN.HP.JK.UK",
    "WB.OR",
    "MUM.PUNE",
    "DL.NCR",
    "KA",
    "AP.TL",
    "UP.BR.JH",
    "Sri Lanka"
  ];

  List<dynamic> divisionNewList = [
    "South-West",
    "North-East"
  ];

  List<dynamic> categoryNewList = [
    "South-West1",
    "North-East1"
  ];

  List<dynamic> brandNewList = [
    "South-West2",
    "North-East2"
  ];

  List<dynamic> brandformNewList = [
    "South-West3",
    "North-East3"
  ];

  List<dynamic> subBFNewList = [
    "South-West4",
    "North-East4"
  ];
}
