// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDU1EisvfVd3LB8vFBI7dOyEsipayaXQ',
    appId: '1:966656788419:web:875cb09c977378a51c5f76',
    messagingSenderId: '966656788419',
    projectId: 'comandc-99a4a',
    authDomain: 'comandc-99a4a.firebaseapp.com',
    storageBucket: 'comandc-99a4a.appspot.com',
    measurementId: 'G-F3G4J9C5L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27DopIenlyV-E_BD7g1Lgk8mEJQaoUgE',
    appId: '1:966656788419:android:045e731bcc7b42961c5f76',
    messagingSenderId: '966656788419',
    projectId: 'comandc-99a4a',
    storageBucket: 'comandc-99a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP4CdUd7FnrgcspZqGRXsqkogzngFaSnk',
    appId: '1:966656788419:ios:eec3a33363e99cae1c5f76',
    messagingSenderId: '966656788419',
    projectId: 'comandc-99a4a',
    storageBucket: 'comandc-99a4a.appspot.com',
    iosBundleId: 'tranzita.commandcentre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP4CdUd7FnrgcspZqGRXsqkogzngFaSnk',
    appId: '1:966656788419:ios:c1eee802c9ed66f11c5f76',
    messagingSenderId: '966656788419',
    projectId: 'comandc-99a4a',
    storageBucket: 'comandc-99a4a.appspot.com',
    iosBundleId: 'tranzita.pgMumbaiCommandCentreMobile.RunnerTests',
  );
}
