// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDtUkt2Jtl8UCl0C-JT1lbQJSHUYhk1hE',
    appId: '1:589025977698:web:d7d9e64bf1eddad237383b',
    messagingSenderId: '589025977698',
    projectId: 'command-center-6b1dc',
    authDomain: 'command-center-6b1dc.firebaseapp.com',
    storageBucket: 'command-center-6b1dc.appspot.com',
    measurementId: 'G-7TJKGZZLFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnaufQD9LJn1vl2i63mwL41jy15_FUEqw',
    appId: '1:589025977698:android:fb51835de8a7760f37383b',
    messagingSenderId: '589025977698',
    projectId: 'command-center-6b1dc',
    storageBucket: 'command-center-6b1dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2VbnloYNFeAluSc2GN3kN8O7h9933xU',
    appId: '1:589025977698:ios:0383887986812c0b37383b',
    messagingSenderId: '589025977698',
    projectId: 'command-center-6b1dc',
    storageBucket: 'command-center-6b1dc.appspot.com',
    iosBundleId: 'com.example.pgCommandCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2VbnloYNFeAluSc2GN3kN8O7h9933xU',
    appId: '1:589025977698:ios:0383887986812c0b37383b',
    messagingSenderId: '589025977698',
    projectId: 'command-center-6b1dc',
    storageBucket: 'command-center-6b1dc.appspot.com',
    iosBundleId: 'com.example.pgCommandCenter',
  );
}
